dependencies:
  - numpy==1.16.2
  - scipy==1.2.1
  - matplotlib==3.0.3
  - seaborn==0.9.0
  - pandas==0.23.4
  - scikit-learn==0.20.3
  - tsfresh==0.11.2
  - statsmodels==0.9.0
  - nltk==3.4
  - tqdm==4.31.1
